# Close match to CircleCI's test environment
FROM ubuntu:12.04

RUN groupadd -r postgres && useradd -r -g postgres postgres
ADD circleci/*.sh /home/postgres/pg8000/circleci/
RUN mkdir -p /home/postgres/bin && chown -R postgres:postgres /home/postgres
WORKDIR /home/postgres/pg8000

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y libossp-uuid16 libossp-uuid-dev libssl-dev wget bzip2 \
    libreadline-dev libgss3 libgss-dev libxml2 libxml2-dev libkrb5-3 libkrb5-dev build-essential \
    ca-certificates unzip openjdk-7-jre-headless python-pip && \
  pip install tox && \
  su postgres -c " \
  bash ./circleci/install-postgresql-9.1.22.sh && \
  bash ./circleci/install-postgresql-9.2.17.sh && \
  bash ./circleci/install-postgresql-9.3.13.sh && \
  bash ./circleci/install-postgresql-9.4.8.sh && \
  bash ./circleci/install-postgresql-9.5.3.sh && \
  bash ./circleci/install-python-2.7.9.sh && \
  bash ./circleci/install-python-3.3.5.sh && \
  bash ./circleci/install-python-3.4.2.sh && \
  bash ./circleci/install-python-3.5.1.sh && \
  bash ./circleci/install-pypy-2.4.0.sh && \
  bash ./circleci/install-pypy3-2.3.1.sh && \
  bash ./circleci/install-jython-2.7.0.sh \
  " && \
  DEBIAN_FRONTEND=noninteractive apt-get remove -y libossp-uuid-dev wget bzip2 libreadline-dev \
    libgss-dev libxml2-dev libkrb5-dev build-essential unzip && \
  DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
  rm -rf /var/lib/apt/lists/*

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/postgres/bin

ENV PG8000_TEST_NAME=PG8000_TEST_9_5
ENV PG8000_TEST_9_1="{\"user\": \"postgres\", \"password\": \"pw\", \"port\": 5491}"
ENV PG8000_TEST_9_2="{\"user\": \"postgres\", \"password\": \"pw\", \"port\": 5492}"
ENV PG8000_TEST_9_3="{\"user\": \"postgres\", \"password\": \"pw\", \"port\": 5493}"
ENV PG8000_TEST_9_4="{\"user\": \"postgres\", \"password\": \"pw\", \"port\": 5494}"
ENV PG8000_TEST_9_5="{\"user\": \"postgres\", \"password\": \"pw\", \"port\": 5495}"

USER postgres
CMD bash ./circleci/run-postgres-and-tox.sh
